### PR TITLE
Add prow and adjust pre-commit

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by goern** [comment]
could you move the ptyest form aicoe-ci to prow too? and remove .zuul? :)

**Comment by pacospace** [comment]
> could you move the ptyest form aicoe-ci to prow too? and remove .zuul? :)

Done :)

**Comment by pacospace** [comment]
why PRs are not merged automatically @goern ?

**Pull request merged**
