### PR TITLE
Add new release to PR template

### PR DESCRIPTION
**Pull request by mayaCostantini**
## This introduces a breaking change

- No

### CODE REVIEW

**Comment by pacospace** [comment]
should have this update at thoth template level? cc @codificat @mayaCostantini

**Comment by mayaCostantini** [comment]
@pacospace I agree, we could unify the template for all repos where new releases are needed 👍🏻

**Comment by mayaCostantini** [comment]
/close
Replaced by https://github.com/thoth-station/.github/pull/3

**Comment by mayaCostantini** [comment]
/close
Let's make the change in the `.github` repo instead

**Pull request closed without merging**
